//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `lighthouse.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dtstep.lighthouse.common.ice;

/** @hidden */
public class _RemoteLightServerPrxI extends com.zeroc.Ice._ObjectPrxI implements RemoteLightServerPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
