// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `lighthouse.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dtstep.lighthouse.common.ice;

public interface AuxInterface extends Ice.Object,
                                      _AuxInterfaceOperations, _AuxInterfaceOperationsNC
{
    public static final String ice_staticId = "::LightHouseServer::AuxInterface";

    public static final long serialVersionUID = -3481776300083825694L;
}
