// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `lighthouse.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dtstep.lighthouse.common.ice;

public interface AuxInterfacePrx extends Ice.ObjectPrx
{
    public String queryGroupByToken(String token);

    public String queryGroupByToken(String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryGroupByToken(String token);

    public Ice.AsyncResult begin_queryGroupByToken(String token, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryGroupByToken(String token, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryGroupByToken(String token, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryGroupByToken(String token, Callback_AuxInterface_queryGroupByToken __cb);

    public Ice.AsyncResult begin_queryGroupByToken(String token, java.util.Map<String, String> __ctx, Callback_AuxInterface_queryGroupByToken __cb);

    public Ice.AsyncResult begin_queryGroupByToken(String token,
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb,
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryGroupByToken(String token,
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb,
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_queryGroupByToken(String token,
                                                   java.util.Map<String, String> __ctx,
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb,
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryGroupByToken(String token,
                                                   java.util.Map<String, String> __ctx,
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb,
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public String end_queryGroupByToken(Ice.AsyncResult __result);

    public String queryStatById(int statId);

    public String queryStatById(int statId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryStatById(int statId);

    public Ice.AsyncResult begin_queryStatById(int statId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_queryStatById(int statId, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryStatById(int statId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_queryStatById(int statId, Callback_AuxInterface_queryStatById __cb);

    public Ice.AsyncResult begin_queryStatById(int statId, java.util.Map<String, String> __ctx, Callback_AuxInterface_queryStatById __cb);

    public Ice.AsyncResult begin_queryStatById(int statId,
                                               IceInternal.Functional_GenericCallback1<String> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryStatById(int statId,
                                               IceInternal.Functional_GenericCallback1<String> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_queryStatById(int statId,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_GenericCallback1<String> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_queryStatById(int statId,
                                               java.util.Map<String, String> __ctx,
                                               IceInternal.Functional_GenericCallback1<String> __responseCb,
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                               IceInternal.Functional_BoolCallback __sentCb);

    public String end_queryStatById(Ice.AsyncResult __result);
}
