// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `lighthouse.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dtstep.lighthouse.common.ice;

/**
 * Provides type-specific helper functions.
 **/
public final class AuxInterfacePrxHelper extends Ice.ObjectPrxHelperBase implements AuxInterfacePrx
{
    private static final String __queryGroupByToken_name = "queryGroupByToken";

    public String queryGroupByToken(String token)
    {
        return queryGroupByToken(token, null, false);
    }

    public String queryGroupByToken(String token, java.util.Map<String, String> __ctx)
    {
        return queryGroupByToken(token, __ctx, true);
    }

    private String queryGroupByToken(String token, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__queryGroupByToken_name);
        return end_queryGroupByToken(begin_queryGroupByToken(token, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token)
    {
        return begin_queryGroupByToken(token, null, false, false, null);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, java.util.Map<String, String> __ctx)
    {
        return begin_queryGroupByToken(token, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, Ice.Callback __cb)
    {
        return begin_queryGroupByToken(token, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_queryGroupByToken(token, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, Callback_AuxInterface_queryGroupByToken __cb)
    {
        return begin_queryGroupByToken(token, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, java.util.Map<String, String> __ctx, Callback_AuxInterface_queryGroupByToken __cb)
    {
        return begin_queryGroupByToken(token, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_queryGroupByToken(token, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryGroupByToken(token, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_queryGroupByToken(token, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_queryGroupByToken(String token, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryGroupByToken(token, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_queryGroupByToken(String token, 
                                                    java.util.Map<String, String> __ctx, 
                                                    boolean __explicitCtx, 
                                                    boolean __synchronous, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryGroupByToken(token, __ctx, __explicitCtx, __synchronous, 
                                       new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                           {
                                               public final void __completed(Ice.AsyncResult __result)
                                               {
                                                   AuxInterfacePrxHelper.__queryGroupByToken_completed(this, __result);
                                               }
                                           });
    }

    private Ice.AsyncResult begin_queryGroupByToken(String token, 
                                                    java.util.Map<String, String> __ctx, 
                                                    boolean __explicitCtx, 
                                                    boolean __synchronous, 
                                                    IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__queryGroupByToken_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__queryGroupByToken_name, __cb);
        try
        {
            __result.prepare(__queryGroupByToken_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(token);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_queryGroupByToken(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __queryGroupByToken_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __queryGroupByToken_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        AuxInterfacePrx __proxy = (AuxInterfacePrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_queryGroupByToken(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __queryStatById_name = "queryStatById";

    public String queryStatById(int statId)
    {
        return queryStatById(statId, null, false);
    }

    public String queryStatById(int statId, java.util.Map<String, String> __ctx)
    {
        return queryStatById(statId, __ctx, true);
    }

    private String queryStatById(int statId, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__queryStatById_name);
        return end_queryStatById(begin_queryStatById(statId, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_queryStatById(int statId)
    {
        return begin_queryStatById(statId, null, false, false, null);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, java.util.Map<String, String> __ctx)
    {
        return begin_queryStatById(statId, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, Ice.Callback __cb)
    {
        return begin_queryStatById(statId, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_queryStatById(statId, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, Callback_AuxInterface_queryStatById __cb)
    {
        return begin_queryStatById(statId, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, java.util.Map<String, String> __ctx, Callback_AuxInterface_queryStatById __cb)
    {
        return begin_queryStatById(statId, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_queryStatById(statId, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryStatById(statId, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_queryStatById(statId, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_queryStatById(int statId, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryStatById(statId, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_queryStatById(int statId, 
                                                java.util.Map<String, String> __ctx, 
                                                boolean __explicitCtx, 
                                                boolean __synchronous, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_queryStatById(statId, __ctx, __explicitCtx, __synchronous, 
                                   new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                       {
                                           public final void __completed(Ice.AsyncResult __result)
                                           {
                                               AuxInterfacePrxHelper.__queryStatById_completed(this, __result);
                                           }
                                       });
    }

    private Ice.AsyncResult begin_queryStatById(int statId, 
                                                java.util.Map<String, String> __ctx, 
                                                boolean __explicitCtx, 
                                                boolean __synchronous, 
                                                IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__queryStatById_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__queryStatById_name, __cb);
        try
        {
            __result.prepare(__queryStatById_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeInt(statId);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_queryStatById(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __queryStatById_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __queryStatById_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        AuxInterfacePrx __proxy = (AuxInterfacePrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_queryStatById(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static AuxInterfacePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), AuxInterfacePrx.class, AuxInterfacePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static AuxInterfacePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), AuxInterfacePrx.class, AuxInterfacePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static AuxInterfacePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), AuxInterfacePrx.class, AuxInterfacePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static AuxInterfacePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), AuxInterfacePrx.class, AuxInterfacePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static AuxInterfacePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, AuxInterfacePrx.class, AuxInterfacePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static AuxInterfacePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, AuxInterfacePrx.class, AuxInterfacePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::LightHouseServer::AuxInterface"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, AuxInterfacePrx v)
    {
        __os.writeProxy(v);
    }

    public static AuxInterfacePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            AuxInterfacePrxHelper result = new AuxInterfacePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
