//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `lighthouse.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dtstep.lighthouse.common.ice;

/**
 * Helper class for marshaling/unmarshaling LongList.
 **/
public final class LongListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, java.util.List<Long> v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.size());
            for(long elem : v)
            {
                ostr.writeLong(elem);
            }
        }
    }

    public static java.util.List<Long> read(com.zeroc.Ice.InputStream istr)
    {
        final java.util.List<Long> v;
        v = new java.util.ArrayList();
        final int len0 = istr.readAndCheckSeqSize(8);
        for(int i0 = 0; i0 < len0; i0++)
        {
            long elem;
            elem = istr.readLong();
            v.add(elem);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<java.util.List<Long>> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.List<Long> v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.size();
            ostr.writeSize(optSize > 254 ? optSize * 8 + 5 : optSize * 8 + 1);
            LongListHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<java.util.List<Long>> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            java.util.List<Long> v;
            v = LongListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
