// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `lighthouse.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.dtstep.lighthouse.common.ice;

public interface ReceiverInterfacePrx extends Ice.ObjectPrx
{
    public String logic(byte[] message);

    public String logic(byte[] message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logic(byte[] message);

    public Ice.AsyncResult begin_logic(byte[] message, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logic(byte[] message, Ice.Callback __cb);

    public Ice.AsyncResult begin_logic(byte[] message, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_logic(byte[] message, Callback_ReceiverInterface_logic __cb);

    public Ice.AsyncResult begin_logic(byte[] message, java.util.Map<String, String> __ctx, Callback_ReceiverInterface_logic __cb);

    public Ice.AsyncResult begin_logic(byte[] message,
                                       IceInternal.Functional_GenericCallback1<String> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logic(byte[] message,
                                       IceInternal.Functional_GenericCallback1<String> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_logic(byte[] message,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_GenericCallback1<String> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_logic(byte[] message,
                                       java.util.Map<String, String> __ctx,
                                       IceInternal.Functional_GenericCallback1<String> __responseCb,
                                       IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb,
                                       IceInternal.Functional_BoolCallback __sentCb);

    public String end_logic(Ice.AsyncResult __result);
}
