FROM eclipse-temurin:11-jre

RUN groupadd -g 1001 lighthouse \
    && useradd -u 1001 -g 1001 -m -s /bin/bash lighthouse

WORKDIR /app

ENV LDP_HOME=/app

COPY docker/lib/lighthouse-*insights*.jar app.jar
COPY docker/lib ./lib

RUN mkdir -p /app/conf

CMD ["java", \
    "-XX:+UseG1GC", \
    "-Duser.timezone=Asia/Shanghai", \
    "-Dfile.encoding=UTF-8", \
    "-Dlog4j.configurationFile=/app/conf/log4j2-standalone.xml", \
    "-Dloader.path=/app/lib", \
    "-Dspring.config.location=file:/app/conf/lighthouse-insights.yml", \
    "-cp", "/app/lib/*:/app/app.jar", \
    "com.dtstep.lighthouse.standalone.executive.LightStandaloneEntrance"]
