FROM eclipse-temurin:11-jre

WORKDIR /app

ENV LDP_HOME=/app

COPY docker/lib/lighthouse-*insights*.jar app.jar
COPY docker/lib ./lib


CMD ["java", "-Dloader.path=/app/lib", "-Dspring.config.location=file:/app/conf/lighthouse-insights.yml", "-jar", "app.jar"]
